version: '3'

services:
    frontend:
        container_name: "frontend"
        build: ./frontend/
        ports:
          - 8888:3000
        command: yarn start

    backend:
        container_name: "backend"
        build: ./backend/
        ports:
          - 8080:8080
        command: yarn start
          
    redis:
      container_name: "redis"
      image: "redis:latest"
      ports:
        - "6380:6379"
      volumes:
        - "./data/redis:/data"